// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloudNimble.PackageReferenceUpgrader
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNuGetUpgraderPackageString = "bb3cf744-1cd9-48e9-a164-52bf34560398";
        public const string guidNuGetUpgraderPackageCmdSetString = "4200e2f1-f5df-4b40-953b-d034cff71951";
        public const string guidImagesString = "fd0ac1d1-60ce-46be-8392-e1c0148b264d";
        public static Guid guidNuGetUpgraderPackage = new Guid(guidNuGetUpgraderPackageString);
        public static Guid guidNuGetUpgraderPackageCmdSet = new Guid(guidNuGetUpgraderPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int NuGetUpgraderId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
