// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloudNimble.PackageReferenceUpgrader
{
    static class Vsix
    {
        public const string Id = "bae2a4ae-be17-4f34-be32-f7f103918589";
        public const string Name = "NuGet PackageReference Upgrader";
        public const string Description = @"A VS Extension that helps legacy apps migrate off of packages.config.";
        public const string Language = "en-US";
        public const string Version = "1.0.2";
        public const string Author = "Robert McLaws";
        public const string Tags = "web.config, assembly binding redirects, binding redirects, assembly binding";
    }
}
